# Generated by Django 4.2.4 on 2023-08-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoinStatsRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_latest_rsi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_latest_rsi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_adx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_adx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_ema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_ema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_roc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_roc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_beta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_beta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_sma_20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_sma_20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_super_trend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_super_trend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_slope_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_slope_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_intercept', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_intercept', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_r_squared', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_r_squared', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_std_deviation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_std_deviation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_closing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_closing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin')),
            ],
        ),
        migrations.CreateModel(
            name='CoinStatsCalculated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_rsi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sma_20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('super_trend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slope_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intercept', models.DecimalField(decimal_places=2, max_digits=10)),
                ('r_squared', models.DecimalField(decimal_places=2, max_digits=10)),
                ('std_deviation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin')),
            ],
        ),
    ]
