# Generated by Django 4.2.4 on 2023-09-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_coinstatsrange_lower_adx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=6, max_digits=10)),
                ('high', models.DecimalField(decimal_places=6, max_digits=10)),
                ('low', models.DecimalField(decimal_places=6, max_digits=10)),
                ('close', models.DecimalField(decimal_places=6, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=10)),
                ('time', models.DateTimeField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin')),
            ],
        ),
    ]
