# Generated by Django 4.2.4 on 2023-09-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_coindata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coindata',
            unique_together={('coin', 'time')},
        ),
    ]
