# Generated by Django 4.2.4 on 2023-09-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_coindata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindata',
            name='close',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='high',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='low',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='open',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='volume',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
    ]
