# Generated by Django 4.2.4 on 2023-09-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_alter_coindata_close_alter_coindata_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinstatscalculated',
            name='closing_price',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coinstatscalculated',
            name='coin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin'),
        ),
        migrations.AlterField(
            model_name='coinstatscalculated',
            name='intercept',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coinstatscalculated',
            name='r_squared',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coinstatscalculated',
            name='slope_percent',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coinstatscalculated',
            name='std_deviation',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='coin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scanner.coin'),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='lower_closing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='lower_intercept',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='lower_r_squared',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='lower_slope_percent',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='lower_std_deviation',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='upper_closing_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='upper_intercept',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='upper_r_squared',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='upper_slope_percent',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinstatsrange',
            name='upper_std_deviation',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
