# Generated by Django 4.2.4 on 2023-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_coinstatscalculated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinstatscalculated',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
