# Generated by Django 4.2.4 on 2023-09-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
